- name: Installs a package and prints the result
  hosts: all
  environment:
    ansible_host_key_checking: false
  tasks:
  - name: Install the package
    yum:
      name: httpd
      state: installed
    register: install_result
  - debug: var=install_result
